import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class OrderDetailService {

  constructor() { }

  foodDetails= [
    {
      id:6,
      foodName:"F",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 13413,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"food",
      qnt:1,
    },
    {
      id:2,
      foodName:"B",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 100,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:3,
      foodName:"C",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 11111,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:4,
      foodName:"D",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 4444,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:12,
      foodName:"M",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 2100,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"food",
      qnt:1,
    },
    {
      id:5,
      foodName:"E",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 5555,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:1,
      foodName:"Pan-fried masala panner",
      foodDetails:" Pan-fried masala paneer is a better choice for beginning eating for fatas. If you want to enjoy it, I need to click BUY NOW and wait for me , will sended it to you by faster",
      foodPrice: 10000 ,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"food",
      qnt:1,
    },
    {
      id:7,
      foodName:"G",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 124124,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:9,
      foodName:"Y",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 5342321,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:10,
      foodName:"K",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 12111,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"food",
      qnt:1,
    },
    {
      id:11,
      foodName:"L",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 11,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"food",
      qnt:1,
    },
    {
      id:8,
      foodName:"H",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 1242,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"food",
      qnt:1,
    },
    {
      id:13,
      foodName:"N",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 1200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"food",
      qnt:1,
    },
    {
      id:14,
      foodName:"O",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 2200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"food",
      qnt:1,
    },
    {
      id:15,
      foodName:"P",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 2200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"food",
      qnt:1,
    },
    {
      id:16,
      foodName:"Q",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"food",
      qnt:1,
    },
    {
      id:17,
      foodName:"R",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:18,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:19,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:20,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:21,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:22,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:23,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:24,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:25,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:26,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:27,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:28,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"drink",
      qnt:1,
    },
    {
      id:29,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:30,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:31,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:22,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:222,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:2822,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:281,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:28223,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:282,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:284,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:283,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:222,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:212,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
    {
      id:33,
      foodName:"Drink",
      foodDetails:" Pan-fried masala paneer.",
      foodPrice: 3200,
      foodImg:"../../../assets/img/slide2.jpg",
      type:"fruit",
      qnt:1,
    },
  ]

  getFoodById(id:number){
    return this.foodDetails.find(ar => ar.id === id);
  }

  
}
